name: "rails-app-test"

x-common: &common
  env_file:
    - .env.example
    - .env

x-pg-common: &pg-common
  image: postgres:18-alpine
  healthcheck:
    test: ["CMD-SHELL", "pg_isready"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s

x-redis-common: &redis-common
  image: valkey/valkey:8-alpine
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 5s
    timeout: 3s
    retries: 3
    start_period: 3s

x-rails-common: &rails-common
  image: local/rails-app:test
  build:
    context: .
    args:
      RAILS_ENV: test
      BUNDLE_DEPLOYMENT: "false"
      BUNDLE_WITHOUT: ""
      APP_UID: ${APP_UID:-1000}
      APP_GID: ${APP_GID:-1000}
  depends_on:
    pg:
      condition: service_healthy
    redis_cache:
      condition: service_healthy
    redis_session:
      condition: service_healthy

services:
  pg:
    <<: [*common, *pg-common]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${APP_POSTGRES_USER}
      POSTGRES_DB: ${APP_POSTGRES_DB}
  redis_cache:
    <<: [*common, *redis-common]
    command: redis-server --save ""
  redis_session:
    <<: [*common, *redis-common]
    command: redis-server --save ""
  rails:
    <<: [*common, *rails-common]
    environment:
      APP_RAILS_MAX_THREADS: 5
      APP_RAILS_MIN_THREADS: 5
      APP_WEB_CONCURRENCY: 0
      APP_ADMIN_EMAIL: admin@example.com
    develop:
      watch:
        - action: sync
          path: .
          target: /rails
          ignore:
            # Version control
            - .git/
            - .github/

            # Dependencies
            - .bundle/
            - vendor/bundle/

            # Environment & secrets
            - .env*
            - .secrets/

            # Runtime data
            - .srv/
            - log/
            - tmp/
            - storage/

            # Caches
            - .cache/
            - .rubocop-*
            - .ruby-lsp/

            # Editor & IDE
            - .claude/
            - .serena/
            - CLAUDE.md
            - .vscode/
            - .idea/
            - .devcontainer/

            # Docker files
            - .dockerignore
            - Dockerfile*
            - compose.yaml
            - compose.yml
            - compose.*.yaml
            - compose.*.yml

            # Deployment
            - .kamal/
            - bin/deploy
