x-common: &common
  env_file:
    - .env.example
    - .env
  networks:
    - rails_app

x-logging: &default-logging
  driver: local
  options:
    max-size: "50m"
    max-file: "5"
    compress: "true"

x-pg-common: &pg-common
  image: postgres:18-alpine
  healthcheck:
    test: ["CMD-SHELL", "pg_isready"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s
  expose:
    - 5432

x-redis-common: &redis-common
  image: valkey/valkey:8-alpine
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 5s
  expose:
    - 6379

x-rails-common: &rails-common
  image: local/rails_app:latest
  build:
    context: .
    args:
      # Sentry release tracking (optional, for correlating errors with deployments)
      # REVISION is set during Docker build and baked into the image
      REVISION: ${REVISION}

services:
  pg:
    <<: [*common, *pg-common]
    logging: *default-logging
    environment:
      POSTGRES_PASSWORD_FILE: ${APP_POSTGRES_PASSWORD_FILE}
      POSTGRES_USER: ${APP_POSTGRES_USER}
      POSTGRES_DB: ${APP_POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql
    secrets:
      - pg_password
  redis_cache:
    <<: [*common, *redis-common]
    logging: *default-logging
    command:
      - sh
      - -c
      - |
        redis-server \
          --requirepass "$$(cat $$APP_REDIS_CACHE_PASSWORD_FILE)" \
          --maxmemory 1gb \
          --maxmemory-policy allkeys-lru \
          --save ""
    secrets:
      - redis_cache_password
  redis_cable:
    <<: [*common, *redis-common]
    logging: *default-logging
    command:
      - sh
      - -c
      - |
        redis-server \
          --requirepass "$$(cat $$APP_REDIS_CABLE_PASSWORD_FILE)" \
          --maxmemory 512mb \
          --maxmemory-policy noeviction \
          --save ""
    secrets:
      - redis_cable_password
  redis_session:
    <<: [*common, *redis-common]
    logging: *default-logging
    volumes:
      - redis_session_data:/data
    command:
      - sh
      - -c
      - |
        redis-server \
          --requirepass "$$(cat $$APP_REDIS_SESSION_PASSWORD_FILE)" \
          --maxmemory 512mb \
          --maxmemory-policy noeviction \
          --appendonly yes \
          --appendfsync everysec
    secrets:
      - redis_session_password
  redis_queue:
    <<: [*common, *redis-common]
    logging: *default-logging
    volumes:
      - redis_queue_data:/data
    command:
      - sh
      - -c
      - |
        redis-server \
          --requirepass "$$(cat $$APP_REDIS_QUEUE_PASSWORD_FILE)" \
          --maxmemory 512mb \
          --maxmemory-policy noeviction \
          --appendonly yes \
          --appendfsync everysec
    secrets:
      - redis_queue_password
  server:
    <<: [*common, *rails-common]
    logging: *default-logging
    deploy:
      restart_policy:
        condition: on-failure
        delay: 7s
        max_attempts: 10
        window: 120s
    healthcheck:
      test: ['CMD', "curl", "-fsS", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 50s
    stop_signal: SIGTERM
    stop_grace_period: 40s
    volumes:
      - server_storage:/rails/storage
    secrets:
      - pg_password
      - redis_cache_password
      - redis_cable_password
      - redis_session_password
      - redis_queue_password
      - rails_secret_key_base
      - mailer_smtp_password
  worker:
    <<: [*common, *rails-common]
    logging: *default-logging
    deploy:
      restart_policy:
        condition: on-failure
        delay: 7s
        max_attempts: 10
        window: 120s
    healthcheck:
      test: ['CMD', 'pgrep', '-f', 'sidekiq']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    stop_signal: SIGTERM
    stop_grace_period: 40s
    environment:
      APP_DB_MIGRATION: "false"
    volumes:
      - server_storage:/rails/storage
    command: ["./bin/jobs"]
    secrets:
      - pg_password
      - redis_cache_password
      - redis_cable_password
      - redis_session_password
      - redis_queue_password
      - rails_secret_key_base
      - mailer_smtp_password
  cloudflared:
    <<: [*common]
    image: cloudflare/cloudflared:latest
    logging: *default-logging
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "--metrics", "localhost:2000", "ready"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: tunnel --metrics 0.0.0.0:2000 run --token-file /run/secrets/cf_tunnel_token
    secrets:
      - cf_tunnel_token

volumes:
  pg_data:
  server_storage:
  redis_session_data:
  redis_queue_data:

secrets:
  pg_password:
    external: true
    name: rails_app_pg_password
  redis_cache_password:
    external: true
    name: rails_app_redis_cache_password
  redis_cable_password:
    external: true
    name: rails_app_redis_cable_password
  redis_session_password:
    external: true
    name: rails_app_redis_session_password
  redis_queue_password:
    external: true
    name: rails_app_redis_queue_password
  rails_secret_key_base:
    external: true
    name: rails_app_rails_secret_key_base
  mailer_smtp_password:
    external: true
    name: rails_app_mailer_smtp_password
  cf_tunnel_token:
    external: true
    name: rails_app_cf_tunnel_token

networks:
  rails_app:
    external: true
